import { Movie, Review, PricingTier } from './types';

export const movies: Movie[] = [
  {
    id: "1",
    title: "Interstellar",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    year: 2014,
    runtime: "2h 49m",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    imdbRating: 8.7,
    rtRating: 73,
    synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=2694&auto=format&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=2672&auto=format&fit=crop",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper", avatar: "https://i.pravatar.cc/150?u=mc" },
      { name: "Anne Hathaway", role: "Brand", avatar: "https://i.pravatar.cc/150?u=ah" }
    ],
    isTrending: true,
    isTopRated: true
  },
  {
    id: "2",
    title: "Blade Runner 2049",
    tagline: "There are still pages left to be turned.",
    year: 2017,
    runtime: "2h 44m",
    genres: ["Sci-Fi", "Action"],
    imdbRating: 8.0,
    rtRating: 88,
    synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    poster: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=2670&auto=format&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1613679074971-91ea27180061?q=80&w=2670&auto=format&fit=crop",
    cast: [
      { name: "Ryan Gosling", role: "K", avatar: "https://i.pravatar.cc/150?u=rg" },
      { name: "Harrison Ford", role: "Deckard", avatar: "https://i.pravatar.cc/150?u=hf" }
    ],
    isTrending: true,
    isNew: true
  },
  {
    id: "3",
    title: "Dune: Part Two",
    tagline: "Long live the fighters.",
    year: 2024,
    runtime: "2h 46m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 8.8,
    rtRating: 95,
    synopsis: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    poster: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=2670&auto=format&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2672&auto=format&fit=crop",
    cast: [
      { name: "Timothée Chalamet", role: "Paul", avatar: "https://i.pravatar.cc/150?u=tc" },
      { name: "Zendaya", role: "Chani", avatar: "https://i.pravatar.cc/150?u=z" }
    ],
    isTrending: true,
    isNew: true,
    isTopRated: true
  },
  {
    id: "4",
    title: "The Grand Budapest Hotel",
    tagline: "A perfectly orchestrated comedy.",
    year: 2014,
    runtime: "1h 39m",
    genres: ["Comedy", "Adventure"],
    imdbRating: 8.1,
    rtRating: 92,
    synopsis: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years.",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=2574&auto=format&fit=crop",
    backdrop: "https://images.unsplash.com/photo-1542204172-55af330f5bf1?q=80&w=2574&auto=format&fit=crop",
    cast: [
      { name: "Ralph Fiennes", role: "Gustave", avatar: "https://i.pravatar.cc/150?u=rf" }
    ],
    isTopRated: true
  },
  {
    id: "5",
    title: "Shadow Protocol",
    tagline: "Trust is a luxury you can't afford.",
    year: 2023,
    runtime: "2h 15m",
    genres: ["Thriller", "Action"],
    imdbRating: 7.9,
    rtRating: 84,
    synopsis: "In a world of digital espionage, a rogue agent must uncover a global conspiracy before the system shuts down for good.",
    poster: "/src/assets/images/regenerated_image_1778219924620.png",
    backdrop: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=2525&auto=format&fit=crop",
    cast: [{ name: "Alex Rivera", role: "Agent Shadow", avatar: "https://i.pravatar.cc/150?u=ar" }],
    isTrending: true,
    isNew: true
  },
  {
    id: "6",
    title: "Neon Nights",
    tagline: "Lost in the rhythm of the city.",
    year: 2024,
    runtime: "1h 55m",
    genres: ["Drama", "Music"],
    imdbRating: 8.2,
    rtRating: 91,
    synopsis: "A struggling musician finds inspiration in the vibrant underground scene of Tokyo's neon-lit districts.",
    poster: "/src/assets/images/regenerated_image_1778219925272.png",
    backdrop: "https://images.unsplash.com/photo-1542204172-55af330f5bf1?q=80&w=2574&auto=format&fit=crop",
    cast: [{ name: "Hana Sato", role: "Mei", avatar: "https://i.pravatar.cc/150?u=hs" }],
    isTrending: true,
    isNew: true
  },
  {
    id: "7",
    title: "The Last Frontier",
    tagline: "Where the mountains meet the sky.",
    year: 2022,
    runtime: "2h 30m",
    genres: ["Adventure", "Western"],
    imdbRating: 7.6,
    rtRating: 78,
    synopsis: "An epic journey across the untamed wilderness of the early American West in search of a legendary lost valley.",
    poster: "/src/assets/images/regenerated_image_1778219926389.png",
    backdrop: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2670&auto=format&fit=crop",
    cast: [{ name: "John Miller", role: "The Guide", avatar: "https://i.pravatar.cc/150?u=jm" }],
    isTopRated: true
  },
  {
    id: "8",
    title: "Celestial Echoes",
    tagline: "Listen to the stars.",
    year: 2023,
    runtime: "2h 05m",
    genres: ["Sci-Fi", "Mystery"],
    imdbRating: 8.4,
    rtRating: 89,
    synopsis: "A team of scientists decipher a mysterious signal from a distant galaxy that challenges everything they know about physics.",
    poster: "/src/assets/images/regenerated_image_1778219927122.png",
    backdrop: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2672&auto=format&fit=crop",
    cast: [{ name: "Sarah Chen", role: "Dr. Wu", avatar: "https://i.pravatar.cc/150?u=sc" }],
    isTrending: true,
    isTopRated: true
  },
  {
    id: "9",
    title: "Velvet Horizons",
    tagline: "Every secret has a weight.",
    year: 2021,
    runtime: "2h 12m",
    genres: ["Romance", "Drama"],
    imdbRating: 7.3,
    rtRating: 81,
    synopsis: "Two strangers find themselves connected by a mysterious heirloom in the heart of Paris.",
    poster: "/src/assets/images/regenerated_image_1778219927831.png",
    backdrop: "https://images.unsplash.com/photo-1493134795733-974e402c8466?q=80&w=2670&auto=format&fit=crop",
    cast: [{ name: "Elena Laurent", role: "Sophie", avatar: "https://i.pravatar.cc/150?u=el" }],
    isTopRated: true
  },
  {
    id: "10",
    title: "The Clockmaker",
    tagline: "Time is ticking for everyone.",
    year: 2023,
    runtime: "1h 48m",
    genres: ["Fantasy", "Family"],
    imdbRating: 7.8,
    rtRating: 86,
    synopsis: "A young apprentice discovers that his master's clocks can actually control the flow of time in their small village.",
    poster: "/src/assets/images/regenerated_image_1778219928643.png",
    backdrop: "https://images.unsplash.com/photo-1508962914676-134849a727f0?q=80&w=2670&auto=format&fit=crop",
    cast: [{ name: "Thomas Wright", role: "The Master", avatar: "https://i.pravatar.cc/150?u=tw" }],
    isNew: true
  },
  {
    id: "11",
    title: "Beyond the Void",
    tagline: "Journey to the edge of existence.",
    year: 2024,
    runtime: "2h 25m",
    genres: ["Sci-Fi", "Horror"],
    imdbRating: 8.1,
    rtRating: 90,
    synopsis: "A space crew encounters an incomprehensible force while exploring the furthest reaches of the observable universe.",
    poster: "/src/assets/images/regenerated_image_1778219929469.png",
    backdrop: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=2672&auto=format&fit=crop",
    cast: [{ name: "David Stark", role: "Captain", avatar: "https://i.pravatar.cc/150?u=ds" }],
    isTrending: true,
    isNew: true
  },
  {
    id: "12",
    title: "Emerald Dreams",
    tagline: "Nature has its own agenda.",
    year: 2022,
    runtime: "1h 42m",
    genres: ["Nature", "Documentary"],
    imdbRating: 8.9,
    rtRating: 98,
    synopsis: "An immersive exploration of the world's most pristine rainforests and the creatures that call them home.",
    poster: "/src/assets/images/regenerated_image_1778219930180.png",
    backdrop: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2574&auto=format&fit=crop",
    cast: [{ name: "Nature Itself", role: "The Earth", avatar: "https://i.pravatar.cc/150?u=nature" }],
    isTopRated: true
  },
  {
    id: "13",
    title: "Iron Symphony",
    tagline: "The industrial revolution reimagined.",
    year: 2023,
    runtime: "2h 08m",
    genres: ["Animation", "Sci-Fi"],
    imdbRating: 8.5,
    rtRating: 94,
    synopsis: "In a steampunk future, a young inventor builds a mechanical orchestra that captures the souls of those who hear it.",
    poster: "/src/assets/images/regenerated_image_1778219931004.png",
    backdrop: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2670&auto=format&fit=crop",
    cast: [{ name: "Leo DaVinci", role: "Inventor", avatar: "https://i.pravatar.cc/150?u=leo" }],
    isTrending: true,
    isTopRated: true
  },
  {
    id: "14",
    title: "Frozen Echoes",
    tagline: "The cold never forgets.",
    year: 2021,
    runtime: "1h 58m",
    genres: ["Drama", "Thriller"],
    imdbRating: 7.2,
    rtRating: 75,
    synopsis: "A search and rescue team gets stranded in the Arctic circle with a threat they didn't see coming.",
    poster: "/src/assets/images/regenerated_image_1778219931822.png",
    backdrop: "https://images.unsplash.com/photo-1516912481808-3b043c127fb4?q=80&w=2574&auto=format&fit=crop",
    cast: [{ name: "Mike Frost", role: "Leader", avatar: "https://i.pravatar.cc/150?u=mf" }],
    isTrending: false
  },
  {
    id: "15",
    title: "Golden Hour",
    tagline: "Moments worth living for.",
    year: 2023,
    runtime: "1h 50m",
    genres: ["Drama", "Life"],
    imdbRating: 8.0,
    rtRating: 88,
    synopsis: "A retired photographer reflects on his career while traveling back to his hometown for one last assignment.",
    poster: "/src/assets/images/regenerated_image_1778219932752.png",
    backdrop: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=2670&auto=format&fit=crop",
    cast: [{ name: "Robert Page", role: "The Artist", avatar: "https://i.pravatar.cc/150?u=rp" }],
    isNew: true,
    isTopRated: true
  }
];

export const reviews: Review[] = [
  { id: "1", name: "Sarah J.", avatar: "https://i.pravatar.cc/150?u=1", rating: 5, quote: "The streaming quality is unmatched. 4K HDR looks incredible on my OLED TV!" },
  { id: "2", name: "Michael R.", avatar: "https://i.pravatar.cc/150?u=2", rating: 5, quote: "Finally, a platform that respects the cinematic aspect ratio. A film lover's dream." },
  { id: "3", name: "Elena Q.", avatar: "https://i.pravatar.cc/150?u=3", rating: 5, quote: "The curated collections helped me find my new favorite indie director." }
];

export const pricingTiers: PricingTier[] = [
  { id: "basic", name: "Basic", price: 0, features: ["720p Streaming", "1 Out of 1000 Titles", "Ad-supported", "1 Device"] },
  { id: "standard", name: "Standard", price: 9.99, features: ["1080p Full HD", "Full Catalogue", "No Ads", "2 Devices", "Download Feature"], isPopular: true },
  { id: "premium", name: "Premium", price: 14.99, features: ["4K + HDR Streaming", "Exclusive Early Access", "Spatial Audio", "4 Devices", "Priority Support"] }
];
